### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ngergs** [cfjhallgren/inkpca#1]
Thanks for your nice work!

Did you already make up your mind about which license is going to being applied for this?
Just curious if I'd be able to apply it for my own work.

**Comment by fredhallgren** [comment]
Thanks! 

Good question. Probably a very permissible license like LGPL. Let me double-check with the university and get back.

**Comment by fredhallgren** [comment]
Apache license it is! Let me know if you have any questions about the code.
